name = "synchroedit"
main = "src-worker/index.js"
compatibility_date = "2026-06-10"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*", "/ws/*"]

[[d1_databases]]
binding = "DB"
database_name = "synchroedit-db"
database_id = "22d0142f-5997-4622-bd2d-33eab48beeea"
migrations_dir = "migrations"

[[durable_objects.bindings]]
name = "DOCUMENT_SYNC_OBJECT"
class_name = "SynchroDocumentObject"

[[durable_objects.bindings]]
name = "RATE_LIMIT_OBJECT"
class_name = "SynchroRateLimitObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SynchroDocumentObject"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["SynchroRateLimitObject"]

[vars]
EMAIL_FROM = "SyncroEdit <no-reply@syncroedit.online>"
APP_NAME = "SyncroEdit"
APP_URL = "https://syncroedit.online"

[env.staging]
name = "synchroedit-dev"
workers_dev = true

[[env.staging.d1_databases]]
binding = "DB"
database_name = "synchroedit-dev-db"
database_id = "11ebe7c6-b238-43bd-906a-6a1fc651156f"
migrations_dir = "migrations"

[[env.staging.durable_objects.bindings]]
name = "DOCUMENT_SYNC_OBJECT"
class_name = "SynchroDocumentObject"

[[env.staging.durable_objects.bindings]]
name = "RATE_LIMIT_OBJECT"
class_name = "SynchroRateLimitObject"

[env.staging.vars]
EMAIL_FROM = "SyncroEdit <no-reply@syncroedit.online>"
APP_NAME = "SyncroEdit"
APP_URL = "https://synchroedit-dev.jordanvorster404.workers.dev"
